[package]
name = "hash_to_curve"
type = "lib"
authors = ["skaunov"]
compiler_version = ">=0.18.0"

[dependencies]
curves = { tag = "v0.2.0", git = "https://github.com/shuklaayush/noir-bigint", directory="crates/curves" }
biguint = { tag = "v0.2.0", git = "https://github.com/shuklaayush/noir-bigint", directory="crates/biguint" }
